### PR TITLE
Archived VilniusPHP 0x2A. Added new event VilniusPHP 0x2B.

### PR DESCRIPTION
**Pull request by sergej-kurakin**
Archived VilniusPHP 0x2A. Added new event VilniusPHP 0x2B with two speakers anounced, changed event place, after-party place and sponsor. Hope everything is done right.

### CODE REVIEW

**Comment by Pawka** [comment]
@sergej-kurakin Can you add linkedin profiles as well? Thanks!

**Comment by Pawka** [comment]
P.S. https://de.linkedin.com/in/adamterlson and https://de.linkedin.com/in/lstrojny

**Comment by sergej-kurakin** [comment]
Added links to speakers LlinkedIn profiles.

**Comment by Pawka** [comment]
Thank You!

**Pull request merged**
